# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10
  identifier = "submenu_bio"
# Sub-menu
       [[main]]
         name = "biosketch & cv"
         url = "#about"
         weight = 11
         parent = "submenu_bio" 
       [[main]]
         name = "experience"
         url = "#experience"
         weight = 12
         parent = "submenu_bio"
      [[main]]
         name = "contact Ian"
         url = "#contact"
         weight = 13
         parent = "submenu_bio"

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20
  identifier = "submenu_pubs"
# Sub-menu
       [[main]]
         name = "featured publications"
         url = "#featured"
         weight = 21
         parent = "submenu_pubs"
       [[main]]
         name = "all publications"
         url = "#publications"
         weight = 22
         parent = "submenu_pubs"

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Teaching"
  url = "#talks"
  weight = 40
  identifier = "submenu_teaching"
# Sub-menu
#       [[main]]
#         name = "courses"
#         url = "#talks"
#         weight = 51
#         parent = "submenu_training"       
#        [[main]]
#         name = "presentations"
#         url = "#talks"
#         weight = 42
#         parent = "submenu_teaching"

# [[main]]
#  name = "Experience"
#  url = "#experience"
#  weight = 20

# [[main]]
#  name = "Featured Articles"
#  url = "#featured"
#  weight = 30

# [[main]]
#   name = "Data Blog"
#   url = "#posts"
#   weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
